name: Static checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdlint $(git ls-files '*.gd')
